import { Poppins } from "next/font/google";
import "../../globals.css";
import Sidebar from "@/app/components/admin-components/sidebar";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminRootLayout({ children }) {
  return (
    <html>
      <body className={poppins.className}>
        <section className="flex flex-row w-full">
            <div>
                <Sidebar/>
            </div>
            <div className="w-full">
                {children}
            </div>
        </section>
        </body>
    </html>
  );
}
